/** Typed backend client. Screens may still use `src/mocks` until wired. */
export { client } from './client'
export { ApiError, unwrap, unwrapOk } from './http'
export { getHealth } from './health'
export {
  getAuditEvent,
  listAudit,
  type AuditEvent,
  type AuditEventDetail,
  type AuditListResponse,
  type ListAuditQuery,
} from './audit'
export {
  allowApproval,
  allowApprovalTemporary,
  denyApproval,
  getApproval,
  listApprovals,
  type AllowTemporaryBody,
  type Approval,
  type ApprovalResolution,
  type ApprovalsListResponse,
  type DenyApprovalBody,
  type ListApprovalsQuery,
} from './approvals'
export {
  getOverview,
  type AgentSplitRow,
  type CallsBucket,
  type DecisionSplitRow,
  type Overview,
  type OverviewQuery,
  type OverviewResponse,
  type QuotaUsage,
} from './overview'
export {
  attachAgentMcp,
  authAgentMcp,
  createAgent,
  createAgentKey,
  createQuota,
  createRule,
  deleteRule,
  detachAgentMcp,
  dryRunRules,
  getAgent,
  getAgentOverview,
  getAgentPosture,
  getRulesMeta,
  listAgents,
  listQuotas,
  listRules,
  patchAgent,
  patchQuota,
  revokeAgent,
  updateRule,
  type Agent,
  type AgentCreate,
  type AgentOverview,
  type AgentOverviewQuery,
  type AgentPatch,
  type AgentPosture,
  type AgentWithKey,
  type AgentsPage,
  type DryRunBody,
  type DryRunResult,
  type EffectiveTool,
  type ListAgentsQuery,
  type Quota,
  type QuotaCreate,
  type QuotaPatch,
  type Rule,
  type RuleBody,
  type RulesMeta,
} from './agents'
export {
  archiveRole,
  createRole,
  getRole,
  listRoles,
  patchRole,
  publishRole,
  type GrantInput,
  type ListRolesQuery,
  type Role,
  type RoleCreate,
  type RoleGrant,
  type RolePatch,
  type RoleSummary,
  type RolesPage,
} from './roles'
export {
  createHostedServer,
  createRemoteServer,
  deleteServer,
  discoverHostedServer,
  discoverRemoteServer,
  getServer,
  listHostedSourceOptions,
  listServers,
  patchServer,
  patchServerTool,
  type HostedAuthMethod,
  type HostedCreateBody,
  type HostedDiscoverBody,
  type HostedDiscoverResult,
  type HostedSourceKind,
  type HostedSourceOption,
  type ListServersQuery,
  type PatchServerBody,
  type PatchServerToolBody,
  type ProposedHostedTool,
  type ProposedToolRisk,
  type RemoteCreateBody,
  type RemoteDiscoverBody,
  type RemoteDiscoverResult,
  type Server,
  type ServerHealth,
  type ServerToolDetail,
  type ServersPage,
} from './mcp'
export {
  disableOperator,
  enableOperator,
  getWorkspace,
  inviteOperator,
  listOperators,
  patchWorkspace,
  resendOperatorInvite,
  type InviteOperatorBody,
  type InviteOperatorRole,
  type ListOperatorsQuery,
  type Operator,
  type OperatorRole,
  type OperatorStatus,
  type OperatorsPage,
  type Workspace,
  type WorkspacePatch,
} from './settings'
export { getMe, type Profile } from './profile'
export {
  getSpecialist,
  listSpecialists,
  type Specialist as ApiSpecialist,
  type SpecialistsPage,
} from './specialists'
export type { ApiBody, ApiQuery, ApiResponse, Schema } from './types'
